In [1]:
import os
os.listdir()

['p1.py',
 '.DS_Store',
 'p7-geocode.ipynb',
 'Untitled.ipynb',
 'p4-translator.py',
 'p3-related.txt',
 'p6-related.txt',
 'p6-pandas.ipynb',
 '.ipynb_checkpoints',
 'p4-related.json',
 'p3.py',
 'p8-related.png',
 'p3-related.csv',
 'p2-related.txt',
 'p2.py',
 'p7-related.xlsx']

In [15]:
import numpy
n = numpy.arange(9)
print(n)

[0 1 2 3 4 5 6 7 8]


In [16]:
n = n.reshape(3,3)

In [18]:
type(n)

numpy.ndarray

In [29]:
import cv2
img = cv2.imread("p8-related.png", 0)
# 0 means Grayscale , 1 means BGR.
# We just converted a image to a numpy array.

In [30]:
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [32]:
cv2.imwrite("p8-relatedGray.png", img)
# We just converted a numpy array to a image file.

True

In [43]:
# Indexing adn Slicing in numpy array
img[1,2] # gets specific index.
img[1:3,:] # gets all col values from 1,2 index rows.
img[:,0:2] # gets all row values from 0,1 index cols.
img[:,:] # gets all.

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [50]:
# Iteration in numpy array.
for i in img: # iterate over rows.
    print(i)
for i in img.flat: # iterate over each ele.
    print(i)

In [51]:
# Stacking in numpy arrays.
# Shape of arrays should be same to stacking them together.
img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [55]:
numpy.hstack((img,img)) # Horizontal Stacking.

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [56]:
numpy.vstack((img,img)) # Vertical Stacking.

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [60]:
# Spliting in numpy arrays.
imgs = numpy.vstack((img, img))
imgs

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [66]:
numpy.vsplit(imgs,2) # Vertical split in 2 arrays.

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [68]:
numpy.hsplit(imgs,5) # Horizontal split in 5 arrays.

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [ ]:
# Exit